//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ParkWhere.Models
{
    public partial class ParkingHistory
    {
        [Display(Name = "Parking History ID")]
        public int parkingHistoryId { get; set; }

        [Display(Name = "Carpark ID")]
        public Nullable<int> carparkId { get; set; }

        [Display(Name = "Username")]
        public string username { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "Parked Date")]
        public DateTime date { get; set; }

        [Display(Name = "Description")]
        public string description { get; set; }

        public virtual Carpark Carpark { get; set; }
    }
}
