//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ParkWhere.Models
{
    public partial class PetrolStation
    {
        public int Id { get; set; }
        
        [Display(Name = "Petrol Station Name")]
        public string petrolStationName { get; set; }
        
        [Display(Name = "Petrol Station Address")]
        public string address { get; set; }
        
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
    }
}
